### ISSUE TITLE
no requirements.txt file

### ISSUE THREAD

**Issue by jcpeterson** [revbucket/mister_ed#13] opened 2018-11-12 03:16 UTC
This would be useful for create virtual environments quickly. I use miniconda and base environments don't come with `config` etc installed

**Comment by tianweiy** [comment] 2018-11-12 03:28
That's a good idea. We will try to create a file like that. For me, I use the same conda environment as [https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md](url)+scikit-image. This uses pytorch master branch which has some change to pytorch 0.4.1 but also fix several bugs in the 0.4.1 version.

**Comment by jcpeterson** [comment] 2018-11-12 17:31
Sounds like that should be the requirements list then?

Do those pytorch bugs cause issues in mister_ed if not corrected?

**Comment by tianweiy** [comment] 2018-11-12 19:16
We don't know yet. Last weekend when I implemented the adversarial logit pairing, I try the MSELoss and it sums instead of averages when giving specific parameters. see [URL](https://github.com/pytorch/pytorch/issues/10148).  We later remove all parameters and it works fine now(As the default behavior is mean so that no parameters are needed). In general, the master branch is not needed and we will fix any bugs if there are. But you can use the master branch if you don't want to meet some unknown problems when you change the program.

**Comment by revbucket** [comment] 2018-11-12 19:43
Okay, it's always pretty tricky to get setup working across platforms that I don't have access to. 
I use pip3 everywhere on 3 different machines: (OSX, Ubuntu, ArchLinux), but maybe this doesn't handle things. 

Right now I'll do the following:
1) Build a requirements.txt file (as is standard for pip installs) 
2) Make sure the data download and tutorials run on python2/python3 on clean environments set up using a virtual env: https://docs.python-guide.org/dev/virtualenvs/

I'm not sure about the conda best practices for batch-installing a bunch of requirements, but it seems like there's various scripts out there that _might_ work (https://gist.github.com/luiscape/19d2d73a8c7b59411a2fb73a697f5ed4) 

If there's a preferred way for conda users to list and install dependencies, could you point me to it?

**Comment by revbucket** [comment] 2018-11-12 20:34
Alright, I've built a requirements.txt file that seems to work on a clean install on my end. Please let me know if this works for you and I'll close the issue.

**Comment by jcpeterson** [comment] 2018-11-14 02:29
I thought adversarial logit pairing was refuted/retracted

**Comment by tianweiy** [comment] 2018-11-14 02:37
Yes, I also hear the news on Reddit. I don't know the cause though. In my experiments, while it is a little hard to train, it can get better results when combining with adversarial training(google's released code for imagenet combines both adversarial training and logit pairing). Currently, we add ALP support in alp branch and we will wait to see what happens.

**Comment by jcpeterson** [comment] 2018-11-14 05:20
Oh good to know

**Comment by revbucket** [comment] 2018-11-15 23:31
Closing this for now. 

And as far as ALP goes, I was under the impression this paper was the last word: https://arxiv.org/pdf/1807.10272.pdf 

Additionally, this paper had really nice evaluation visualizations and it's a TODO of mine to get those implemented out of the box with mister_ed. Stay tuned.

**Closed as completed by revbucket** 2018-11-15 23:31 UTC
